# Generated by Django 4.2.11 on 2025-04-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'тег рецепта', 'verbose_name_plural': 'Теги рецепта'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название'),
        ),
    ]
