# Generated by Django 4.2.11 on 2025-05-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_subscription_subscription_unique_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(unique=True, verbose_name='Полная ссылка')),
                ('token', models.CharField(max_length=6, unique=True, verbose_name='Токен короткой ссылки')),
            ],
            options={
                'verbose_name': 'ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='short_link',
        ),
    ]
