# Generated by Django 4.2.11 on 2025-05-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_follow_follow_unique_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
