# Generated by Django 4.2.11 on 2025-05-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('recipes', '0008_subscription_subscription_unique_subscription'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_subscription_delete_myuser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
